site_name: tyron
theme:
    name: material
    font: 
        text: Ubuntu
        code: Ubuntu Mono
    palette:
        primary: teal
        accent: teal
    features:
      - tabs
markdown_extensions:
  - attr_list
repo_url: https://github.com/julio-cabdu/didtyronZIL
site_description: Zilliqa's W3C DID Method
site_author: Tralcan X
copyright: Copyright (C) 2021 Tyron Pungtas
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tyrondid
nav: 
  - Home: 'index.md'
  - W3C DIDs: 'W3C-dids.md'
  - DID Method:
    - Scheme:
      - DID Scheme: 'scheme/did-scheme.md'
      - DID-URL syntax: 'scheme/did-url-syntax.md'
    - DID Document: 'did-document.md'
    - DID CRUD Operations:
      - Create: 'CRUD-operations/did-create.md'
      - Resolve: 'CRUD-operations/did-resolve.md'
      - Recover: 'CRUD-operations/did-recover.md'
      - Update: 'CRUD-operations/did-update.md'
      - Deactivate: 'CRUD-operations/did-deactivate.md'
    - Security & privacy: 'security-privacy.md'
  - Tyron SSI Protocol:
    - Protocol parameters: 'protocol-parameters.md'
    - Smart contracts:
      - DID.tyron: 'smart-contracts/didc.md'
      - init.tyron: 'smart-contracts/init.tyron.md'
  - Implementation:
    - DID Client: 'https://github.com/julio-cabdu/tyronzil-js'
    - Models: 'implementation/models.md'
  - Development: 'roadmap.md'
  
  