site_name: tyronZIL DID method
theme:
    name: material
    font: 
        text: Ubuntu
        code: Ubuntu Mono
    palette:
        primary: teal
    features:
      - tabs
    
repo_url: https://github.com/julio-cabdu/didtyronZIL
site_description: A W3C Sidetree-based DID method for the Zilliqa blockchain platform
site_author: Julio Cabrapan Duarte
copyright: Copyright (C) 2020 Julio Cesar Cabrapan Duarte
nav: 
  - Home: 'index.md'
  - W3C DIDs: 'W3C-dids.md'
  - Sidetree protocol: 'sidetree.md'
  - DID scheme: 'did-scheme.md'
  - DID document: 'did-document.md'
  - 'Operations':
    - 'Operations': 'operations/tyronZIL-operations.md'
    - 'CRUD':
        - 'Create': 'operations/CRUD/did-create.md'
        - 'Resolve': 'operations/CRUD/did-resolve.md'
        - 'Recover': 'operations/CRUD/did-recover.md'
        - 'Update': 'operations/CRUD/did-update.md'
        - 'Deactivate': 'operations/CRUD/did-deactivate.md'
  - 'Implementation':
    - 'tyronZIL-js scheme': 'implementation/tyronZIL-js-scheme.md'
    - 'tyronZIL-js models': 'implementation/models.md'
    - 'GitHub/tyronZIL-js': https://github.com/julio-cabdu/tyronZIL-js
  