site_name: tyronZIL DID-Method
theme:
    name: material
    font: 
        text: Ubuntu
        code: Ubuntu Mono
    palette:
        primary: teal
    features:
      - tabs
markdown_extensions:
  - attr_list
repo_url: https://github.com/julio-cabdu/didtyronZIL
site_description: A W3C Sidetree-based DID method for the Zilliqa blockchain platform
site_author: Julio Cabrapan Duarte
copyright: Copyright (C) 2020 Julio Cesar Cabrapan Duarte
nav: 
  - Home: 'index.md'
  - W3C DIDs: 'W3C-dids.md'
  - Sidetree protocol: 'sidetree.md'
  - DID-Document: 'did-document.md'
  - 'Scheme':
    - 'DID-Scheme': 'scheme/did-scheme.md'
    - 'DID-URL syntax': 'scheme/did-url-syntax.md'
  - 'Operations':
    - 'tyronZIL operations': 'operations/tyronZIL-operations.md'
    - 'DID CRUD':
        - 'Create': 'operations/CRUD/did-create.md'
        - 'Resolve': 'operations/CRUD/did-resolve.md'
        - 'Recover': 'operations/CRUD/did-recover.md'
        - 'Update': 'operations/CRUD/did-update.md'
        - 'Deactivate': 'operations/CRUD/did-deactivate.md'
  - 'Implementation': 'implementation/models.md'
  - Security & privacy: 'security-privacy.md'
  