site_name: tyronzil
theme:
    name: readthedocs
    font: 
        text: Ubuntu
        code: Ubuntu Mono
    palette:
        primary: black
        accent: black
    features:
      - tabs
markdown_extensions:
  - attr_list
repo_url: https://github.com/julio-cabdu/didtyronZIL
site_description: Tyron SSI Protocol's DID Method
site_author: Tralcan X
copyright: Copyright (C) 2021 Tyron Pungtas
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ssiprotocol
nav: 
  - Welcome: 'index.md'
  - W3C DIDs terminology: 'W3C-dids.md'
  - DID Method:
    - Scheme:
      - DID Scheme: 'scheme/did-scheme.md'
      - DID-URL syntax: 'scheme/did-url-syntax.md'
    - DID Document: 'did-document.md'
    - CRUD operations:
      - Create: 'CRUD-operations/did-create.md'
      - Resolve: 'CRUD-operations/did-resolve.md'
      - Recover: 'CRUD-operations/did-recover.md'
      - Update: 'CRUD-operations/did-update.md'
      - Deactivate: 'CRUD-operations/did-deactivate.md'
    - Security & privacy: 'security-privacy.md'
    - Parameters: 'protocol-parameters.md'
    - Models: 'implementation/models.md'
  - Smart contracts:
      - DID.tyron: 'smart-contracts/DID.tyron.md'
      - INIT.tyron: 'smart-contracts/INIT.tyron.md'
  - Implementation:
    - Client: 'https://github.com/tralcanx/tyronzil'
    - Library: 'https://github.com/pungtas/tyron.js'
    - DID Browser: 'https://github.com/pungtas/tyron-react-native'
  - Development: 'roadmap.md'
  
  