site_name: tyron
theme:
    name: material
    font: 
        text: Ubuntu
        code: Ubuntu Mono
    palette:
        primary: teal
        accent: teal
    features:
      - tabs
markdown_extensions:
  - attr_list
repo_url: https://github.com/julio-cabdu/didtyronZIL
site_description: An open-source W3C DID-Method powered by Zilliqa
site_author: Julio Cabrapan Duarte
copyright: Copyright (C) 2020 Julio Cesar Cabrapan Duarte
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tyrondid
nav: 
  - Home: 'index.md'
  - W3C DIDs: 'W3C-dids.md'
  - DID-Method:
    - Scheme:
      - DID-Scheme: 'scheme/did-scheme.md'
      - DID-URL syntax: 'scheme/did-url-syntax.md'
    - DID-Document: 'did-document.md'
    - CRUD Operations:
      - DID-Create: 'CRUD-operations/did-create.md'
      - DID-Resolve: 'CRUD-operations/did-resolve.md'
      - DID-Recover: 'CRUD-operations/did-recover.md'
      - DID-Update: 'CRUD-operations/did-update.md'
      - DID-Deactivate: 'CRUD-operations/did-deactivate.md'
    - Security & privacy: 'security-privacy.md'
  - Tyron DID Protocol:
    - Protocol parameters: 'protocol-parameters.md'
    - Smart contracts:
      - DIDC: 'smart-contracts/didc.md'
      - tyron.init: 'smart-contracts/init.tyron.md'
  - Implementation:
    - DID-Client: 'https://github.com/julio-cabdu/tyronzil-js'
    - Models: 'implementation/models.md'
  - Development: 'roadmap.md'
  
  